name: Merge Schedule

on:
  pull_request:
    types: labeled
  schedule:
    # https://crontab.guru/every-hour
    - cron: '*/5 * * * *'
permissions:
  pull-requests: write
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'automatic' }}
    steps:
      - name: create pull request
        run: |
          gh pr merge --auto -b 'Automatically merged by GitHub'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}