name: Merge Pull Request

on:
  pull_request:
    types: labeled
  schedule:
    # https://crontab.guru/every-hour
    - cron: '*/5 * * * *'
permissions:
  pull-requests: write
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        run: |
          gh pr merge --auto -b 'Automatically merged by our GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}