name: Open Pull Request
on:
  push:
    branches:
      - "development"
permissions:
  pull-requests: write
jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%b %d %Y')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Open Pull Request
        run: |
          gh pr create -B main -H development \
            --title 'Merge Dev into Staging - ${{ env.NOW }}' \
            --body 'Automated PR that will be merged Mondays and Thursdays at 7pm EST.' \
            --label 'automatic'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}