name: Merge Pull Request
on:
  schedule:
    # https://crontab.guru/every-hour
    - cron: '*/5 * * * *'
permissions:
  pull-requests: write
jobs:
  mergePR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge Pull Request
        run: |
          gh pr merge --auto -b 'Automatically merged by our GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}