name: Merge Pull Request
on:
  schedule:
    # https://crontab.guru/every-hour
    - cron: '*/5 * * * *'
permissions:
  pull-requests: write
  contents: write
jobs:
  mergePR:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%b %d %Y')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: development
      - name: List Pull Requests
        run: |
          pr_url=$( gh pr list --limit 1 --label automatic --json labels,id,number,url,state | jq '.[].url')
          echo "PR=$pr_url" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge Pull Request
        run: |
          gh pr merge ${{ env.PR }} --auto -m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}