name: Merge branch with labeled
on:
    schedule:
        - cron:  '0 * * * *'
permissions:
  contents: write
  pull-requests: write 
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge by labeled
        uses: devmasx/merge-branch@master
        with:
          label_name: 'automatic'
          target_branch: 'develop'
          github_token: ${{ github.token }}